name: Terraform GA
on:
  push:
    branches:
      - main
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: downloading the repo
        uses: actions/checkout@v2
      - name: caching the AWS Dependencies
        uses: actions/cache@v3
        id: aws-cache
        with:
          path: |
            ~/.aws
            ~/.aws-sam
          key: ${{ runner.os }}-aws-${{ hashFiles('infrastructure/**') }}
      - name: downloading AWS CLI
        uses: aws-actions/setup-sam@v2
      - name: Setting up the AWS CLI
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-west-2
      - name: caching the terraform dependencies
        uses: actions/cache@v3
        id: terraform-cache
        with:
          path: |
            ~/.terraform.d/plugins
          key: ${{ runner.os }}-terraform-${{ hashFiles('infrastructure/**') }}
      - name: setting up terraform cli
        uses: hashicorp/setup-terraform@v3
      - name: getting into the terraform directory
        run: |
          ls -la
          terraform init
          ls -la
        working-directory: infrastructure
      - name: initializing terraform
        run: |
          terraform validate
          terraform fmt
        working-directory: infrastructure
      - name: planning the terraform resources
        run: |
          terraform plan -out=tfplan
        working-directory: infrastructure