name: Terraform GA
on:
  push:
    branches:
      - main
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: downloading the repo
        uses: actions/checkout@v2
      - name: setting up terraform cli
        uses: hashicorp/setup-terraform@v2
      - name: getting into the terraform directory
        run: |
          ls -la
          cd infrastructure
          ls -la
          terraform validate
          terraform fmt
      - name: initializing terraform
        run: |
          cd terraform
          terraform init