name: Terraform GA
on:
  push:
    branches:
      - main
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: downloading the repo
        uses: actions/checkout@v2
      - name: caching the AWS Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.aws
            ~/.aws-sam
      - name: downloading AWS CLI
        uses: aws-actions/setup-sam@v2
      - name: Setting up the AWS CLI
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-west-2
      - name: caching the terraform dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugins
      - name: setting up terraform cli
        uses: hashicorp/setup-terraform@v2
      - name: getting into the terraform directory
        run: |
          ls -la
          cd infrastructure
          ls -la
          terraform init
      - name: initializing terraform
        run: |
          terraform validate
          terraform fmt